
version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.12

commands:
  setup_working_dir:
    description: get docker initialized and checkout code
    steps:
      - setup_remote_docker
      - checkout
      - run: pip3 install pipenv
      - run: make dev
  lint:
    description: Run flake8
    steps:
      - run: make lint
  test:
    description: Run pytest and generate report
    steps:
      - run: make test
  coverage:
    description: Generate coverage report
    steps:
      - run: make coverage
  build:
    description: build package distribution
    steps:
      - run: make build
jobs:
  lint-and-test:
    executor: python
    steps:
      - setup_working_dir
      - lint
      - test
      - coverage
  build-package:
    executor: python
    steps:
      - setup_working_dir
      - lint
      - test
      - build

workflows:
  test:
    jobs:
      - lint-and-test:
          filters:
            branches:
              ignore: master
  build:
    jobs:
      - build-package:
          filters:
            branches:
              only: master
